name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'poetry'
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          poetry env use "3.12"
          poetry install
      - name: Run Lints
        run: |
          poetry run black nodestream_akamai tests --check
          poetry run isort nodestream_akamai tests --check-only
          poetry run ruff check nodestream_github tests 
      - name: Run Tests
        run: |
          poetry run pytest
